// @generated by protoc-gen-es v2.0.0 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file node/latency/latency.proto (package yuhaiin.latency, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Duration } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_duration } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file node/latency/latency.proto.
 */
export const file_node_latency_latency: GenFile = /*@__PURE__*/
  fileDesc("Chpub2RlL2xhdGVuY3kvbGF0ZW5jeS5wcm90bxIPeXVoYWlpbi5sYXRlbmN5IhMKBGh0dHASCwoDdXJsGAEgASgJIjcKA2RucxIMCgRob3N0GAEgASgJEiIKDXRhcmdldF9kb21haW4YAiABKAlSC3RhcmdldF9uYW1lIkEKDWRuc19vdmVyX3F1aWMSDAoEaG9zdBgBIAEoCRIiCg10YXJnZXRfZG9tYWluGAIgASgJUgt0YXJnZXRfbmFtZSKqAQoIcHJvdG9jb2wSJQoEaHR0cBgBIAEoCzIVLnl1aGFpaW4ubGF0ZW5jeS5odHRwSAASIwoDZG5zGAIgASgLMhQueXVoYWlpbi5sYXRlbmN5LmRuc0gAEkYKDWRuc19vdmVyX3F1aWMYAyABKAsyHi55dWhhaWluLmxhdGVuY3kuZG5zX292ZXJfcXVpY0gAUg1kbnNfb3Zlcl9xdWljQgoKCHByb3RvY29sIl4KB3JlcXVlc3QSCgoCaWQYAyABKAkSDAoEaGFzaBgBIAEoCRIMCgRpcHY2GAQgASgIEisKCHByb3RvY29sGAIgASgLMhkueXVoYWlpbi5sYXRlbmN5LnByb3RvY29sIjYKCHJlcXVlc3RzEioKCHJlcXVlc3RzGAEgAygLMhgueXVoYWlpbi5sYXRlbmN5LnJlcXVlc3QirwEKCHJlc3BvbnNlElMKDmlkX2xhdGVuY3lfbWFwGAEgAygLMisueXVoYWlpbi5sYXRlbmN5LnJlc3BvbnNlLklkTGF0ZW5jeU1hcEVudHJ5Ug5pZF9sYXRlbmN5X21hcBpOChFJZExhdGVuY3lNYXBFbnRyeRILCgNrZXkYASABKAkSKAoFdmFsdWUYAiABKAsyGS5nb29nbGUucHJvdG9idWYuRHVyYXRpb246AjgBQjZaNGdpdGh1Yi5jb20vQXN1dG9ydWZhL3l1aGFpaW4vcGtnL3Byb3Rvcy9ub2RlL2xhdGVuY3liBnByb3RvMw", [file_google_protobuf_duration]);

/**
 * @generated from message yuhaiin.latency.http
 */
export type http = Message<"yuhaiin.latency.http"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message yuhaiin.latency.http.
 * Use `create(httpSchema)` to create a new message.
 */
export const httpSchema: GenMessage<http> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 0);

/**
 * @generated from message yuhaiin.latency.dns
 */
export type dns = Message<"yuhaiin.latency.dns"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: string target_domain = 2 [json_name = "target_name"];
   */
  targetDomain: string;
};

/**
 * Describes the message yuhaiin.latency.dns.
 * Use `create(dnsSchema)` to create a new message.
 */
export const dnsSchema: GenMessage<dns> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 1);

/**
 * @generated from message yuhaiin.latency.dns_over_quic
 */
export type dns_over_quic = Message<"yuhaiin.latency.dns_over_quic"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: string target_domain = 2 [json_name = "target_name"];
   */
  targetDomain: string;
};

/**
 * Describes the message yuhaiin.latency.dns_over_quic.
 * Use `create(dns_over_quicSchema)` to create a new message.
 */
export const dns_over_quicSchema: GenMessage<dns_over_quic> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 2);

/**
 * @generated from message yuhaiin.latency.protocol
 */
export type protocol = Message<"yuhaiin.latency.protocol"> & {
  /**
   * @generated from oneof yuhaiin.latency.protocol.protocol
   */
  protocol: {
    /**
     * @generated from field: yuhaiin.latency.http http = 1;
     */
    value: http;
    case: "http";
  } | {
    /**
     * @generated from field: yuhaiin.latency.dns dns = 2;
     */
    value: dns;
    case: "dns";
  } | {
    /**
     * @generated from field: yuhaiin.latency.dns_over_quic dns_over_quic = 3 [json_name = "dns_over_quic"];
     */
    value: dns_over_quic;
    case: "dnsOverQuic";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message yuhaiin.latency.protocol.
 * Use `create(protocolSchema)` to create a new message.
 */
export const protocolSchema: GenMessage<protocol> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 3);

/**
 * @generated from message yuhaiin.latency.request
 */
export type request = Message<"yuhaiin.latency.request"> & {
  /**
   * @generated from field: string id = 3;
   */
  id: string;

  /**
   * @generated from field: string hash = 1;
   */
  hash: string;

  /**
   * @generated from field: bool ipv6 = 4;
   */
  ipv6: boolean;

  /**
   * @generated from field: yuhaiin.latency.protocol protocol = 2;
   */
  protocol?: protocol;
};

/**
 * Describes the message yuhaiin.latency.request.
 * Use `create(requestSchema)` to create a new message.
 */
export const requestSchema: GenMessage<request> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 4);

/**
 * @generated from message yuhaiin.latency.requests
 */
export type requests = Message<"yuhaiin.latency.requests"> & {
  /**
   * @generated from field: repeated yuhaiin.latency.request requests = 1;
   */
  requests: request[];
};

/**
 * Describes the message yuhaiin.latency.requests.
 * Use `create(requestsSchema)` to create a new message.
 */
export const requestsSchema: GenMessage<requests> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 5);

/**
 * @generated from message yuhaiin.latency.response
 */
export type response = Message<"yuhaiin.latency.response"> & {
  /**
   * @generated from field: map<string, google.protobuf.Duration> id_latency_map = 1 [json_name = "id_latency_map"];
   */
  idLatencyMap: { [key: string]: Duration };
};

/**
 * Describes the message yuhaiin.latency.response.
 * Use `create(responseSchema)` to create a new message.
 */
export const responseSchema: GenMessage<response> = /*@__PURE__*/
  messageDesc(file_node_latency_latency, 6);

