// @generated by protoc-gen-es v2.0.0 with parameter "target=ts"
// @generated from file config/bypass/bypass.proto (package yuhaiin.bypass, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/bypass/bypass.proto.
 */
export const file_config_bypass_bypass: GenFile = /*@__PURE__*/
  fileDesc("Chpjb25maWcvYnlwYXNzL2J5cGFzcy5wcm90bxIOeXVoYWlpbi5ieXBhc3MijQIKDWJ5cGFzc19jb25maWcSIQoDdGNwGAMgASgOMhQueXVoYWlpbi5ieXBhc3MubW9kZRIhCgN1ZHAYBCABKA4yFC55dWhhaWluLmJ5cGFzcy5tb2RlEiAKC2J5cGFzc19maWxlGAIgASgJUgtieXBhc3NfZmlsZRJPCg51ZHBfcHJveHlfZnFkbhgGIAEoDjInLnl1aGFpaW4uYnlwYXNzLnVkcF9wcm94eV9mcWRuX3N0cmF0ZWd5Ug51ZHBfcHJveHlfZnFkbhJDCg5jdXN0b21fcnVsZV92MxgHIAMoCzIbLnl1aGFpaW4uYnlwYXNzLm1vZGVfY29uZmlnUg5jdXN0b21fcnVsZV92MyKXAgoLbW9kZV9jb25maWcSIgoEbW9kZRgBIAEoDjIULnl1aGFpaW4uYnlwYXNzLm1vZGUSCwoDdGFnGAIgASgJEhAKCGhvc3RuYW1lGAMgAygJEkwKEHJlc29sdmVfc3RyYXRlZ3kYBCABKA4yIC55dWhhaWluLmJ5cGFzcy5yZXNvbHZlX3N0cmF0ZWd5UhByZXNvbHZlX3N0cmF0ZWd5EmEKF3VkcF9wcm94eV9mcWRuX3N0cmF0ZWd5GAYgASgOMicueXVoYWlpbi5ieXBhc3MudWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3lSF3VkcF9wcm94eV9mcWRuX3N0cmF0ZWd5SgQIBRAGUg51ZHBfcHJveHlfZnFkbio0CgRtb2RlEgoKBmJ5cGFzcxAAEgoKBmRpcmVjdBABEgkKBXByb3h5EAISCQoFYmxvY2sQAypfChByZXNvbHZlX3N0cmF0ZWd5EgsKB2RlZmF1bHQQABIPCgtwcmVmZXJfaXB2NBABEg0KCW9ubHlfaXB2NBACEg8KC3ByZWZlcl9pcHY2EAMSDQoJb25seV9pcHY2EAQqXQoXdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3kSIwofdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3lfZGVmYXVsdBAAEgsKB3Jlc29sdmUQARIQCgxza2lwX3Jlc29sdmUQAkI3WjVnaXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3MvY29uZmlnL2J5cGFzc2IGcHJvdG8z");

/**
 * @generated from message yuhaiin.bypass.bypass_config
 */
export type bypass_config = Message<"yuhaiin.bypass.bypass_config"> & {
  /**
   * @generated from field: yuhaiin.bypass.mode tcp = 3;
   */
  tcp: mode;

  /**
   * @generated from field: yuhaiin.bypass.mode udp = 4;
   */
  udp: mode;

  /**
   * @generated from field: string bypass_file = 2 [json_name = "bypass_file"];
   */
  bypassFile: string;

  /**
   * @generated from field: yuhaiin.bypass.udp_proxy_fqdn_strategy udp_proxy_fqdn = 6 [json_name = "udp_proxy_fqdn"];
   */
  udpProxyFqdn: udp_proxy_fqdn_strategy;

  /**
   * @generated from field: repeated yuhaiin.bypass.mode_config custom_rule_v3 = 7 [json_name = "custom_rule_v3"];
   */
  customRuleV3: mode_config[];
};

/**
 * Describes the message yuhaiin.bypass.bypass_config.
 * Use `create(bypass_configSchema)` to create a new message.
 */
export const bypass_configSchema: GenMessage<bypass_config> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 0);

/**
 * @generated from message yuhaiin.bypass.mode_config
 */
export type mode_config = Message<"yuhaiin.bypass.mode_config"> & {
  /**
   * @generated from field: yuhaiin.bypass.mode mode = 1;
   */
  mode: mode;

  /**
   * @generated from field: string tag = 2;
   */
  tag: string;

  /**
   * @generated from field: repeated string hostname = 3;
   */
  hostname: string[];

  /**
   * @generated from field: yuhaiin.bypass.resolve_strategy resolve_strategy = 4 [json_name = "resolve_strategy"];
   */
  resolveStrategy: resolve_strategy;

  /**
   * @generated from field: yuhaiin.bypass.udp_proxy_fqdn_strategy udp_proxy_fqdn_strategy = 6 [json_name = "udp_proxy_fqdn_strategy"];
   */
  udpProxyFqdnStrategy: udp_proxy_fqdn_strategy;
};

/**
 * Describes the message yuhaiin.bypass.mode_config.
 * Use `create(mode_configSchema)` to create a new message.
 */
export const mode_configSchema: GenMessage<mode_config> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 1);

/**
 * @generated from enum yuhaiin.bypass.mode
 */
export enum mode {
  /**
   * @generated from enum value: bypass = 0;
   */
  bypass = 0,

  /**
   * @generated from enum value: direct = 1;
   */
  direct = 1,

  /**
   * @generated from enum value: proxy = 2;
   */
  proxy = 2,

  /**
   * @generated from enum value: block = 3;
   */
  block = 3,
}

/**
 * Describes the enum yuhaiin.bypass.mode.
 */
export const modeSchema: GenEnum<mode> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 0);

/**
 * @generated from enum yuhaiin.bypass.resolve_strategy
 */
export enum resolve_strategy {
  /**
   * @generated from enum value: default = 0;
   */
  default = 0,

  /**
   * @generated from enum value: prefer_ipv4 = 1;
   */
  prefer_ipv4 = 1,

  /**
   * @generated from enum value: only_ipv4 = 2;
   */
  only_ipv4 = 2,

  /**
   * @generated from enum value: prefer_ipv6 = 3;
   */
  prefer_ipv6 = 3,

  /**
   * @generated from enum value: only_ipv6 = 4;
   */
  only_ipv6 = 4,
}

/**
 * Describes the enum yuhaiin.bypass.resolve_strategy.
 */
export const resolve_strategySchema: GenEnum<resolve_strategy> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 1);

/**
 * @generated from enum yuhaiin.bypass.udp_proxy_fqdn_strategy
 */
export enum udp_proxy_fqdn_strategy {
  /**
   * @generated from enum value: udp_proxy_fqdn_strategy_default = 0;
   */
  udp_proxy_fqdn_strategy_default = 0,

  /**
   * @generated from enum value: resolve = 1;
   */
  resolve = 1,

  /**
   * @generated from enum value: skip_resolve = 2;
   */
  skip_resolve = 2,
}

/**
 * Describes the enum yuhaiin.bypass.udp_proxy_fqdn_strategy.
 */
export const udp_proxy_fqdn_strategySchema: GenEnum<udp_proxy_fqdn_strategy> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 2);

