// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file config/bypass/bypass.proto (package yuhaiin.bypass, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/bypass/bypass.proto.
 */
export const file_config_bypass_bypass: GenFile = /*@__PURE__*/
  fileDesc("Chpjb25maWcvYnlwYXNzL2J5cGFzcy5wcm90bxIOeXVoYWlpbi5ieXBhc3Mi9QIKBmNvbmZpZxIhCgN0Y3AYAyABKA4yFC55dWhhaWluLmJ5cGFzcy5tb2RlEiEKA3VkcBgEIAEoDjIULnl1aGFpaW4uYnlwYXNzLm1vZGUSJAoLYnlwYXNzX2ZpbGUYAiABKAlCAhgBUgtieXBhc3NfZmlsZRJPCg51ZHBfcHJveHlfZnFkbhgGIAEoDjInLnl1aGFpaW4uYnlwYXNzLnVkcF9wcm94eV9mcWRuX3N0cmF0ZWd5Ug51ZHBfcHJveHlfZnFkbhJDCg5jdXN0b21fcnVsZV92MxgHIAMoCzIbLnl1aGFpaW4uYnlwYXNzLm1vZGVfY29uZmlnUg5jdXN0b21fcnVsZV92MxI/CgxyZW1vdGVfcnVsZXMYCCADKAsyGy55dWhhaWluLmJ5cGFzcy5yZW1vdGVfcnVsZVIMcmVtb3RlX3J1bGVzEigKD3Jlc29sdmVfbG9jYWxseRgJIAEoCFIPcmVzb2x2ZV9sb2NhbGx5IpQDCgttb2RlX2NvbmZpZxIiCgRtb2RlGAEgASgOMhQueXVoYWlpbi5ieXBhc3MubW9kZRILCgN0YWcYAiABKAkSEAoIaG9zdG5hbWUYAyADKAkSTAoQcmVzb2x2ZV9zdHJhdGVneRgEIAEoDjIgLnl1aGFpaW4uYnlwYXNzLnJlc29sdmVfc3RyYXRlZ3lSEHJlc29sdmVfc3RyYXRlZ3kSYQoXdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3kYBiABKA4yJy55dWhhaWluLmJ5cGFzcy51ZHBfcHJveHlfZnFkbl9zdHJhdGVneVIXdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3kSSQoKZXJyb3JfbXNncxgHIAMoCzIqLnl1aGFpaW4uYnlwYXNzLm1vZGVfY29uZmlnLkVycm9yTXNnc0VudHJ5UgllcnJvcl9tc2caMAoORXJyb3JNc2dzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4AUoECAUQBlIOdWRwX3Byb3h5X2ZxZG4i+QEKC3JlbW90ZV9ydWxlEg8KB2VuYWJsZWQYASABKAgSDAoEbmFtZRgCIAEoCRIwCgRmaWxlGAMgASgLMiAueXVoYWlpbi5ieXBhc3MucmVtb3RlX3J1bGVfZmlsZUgAEjAKBGh0dHAYBCABKAsyIC55dWhhaWluLmJ5cGFzcy5yZW1vdGVfcnVsZV9odHRwSAASHAoJZXJyb3JfbXNnGAUgASgJUgllcnJvcl9tc2cSPwoMZGVmYXVsdF9tb2RlGAYgASgLMhsueXVoYWlpbi5ieXBhc3MubW9kZV9jb25maWdSDGRlZmF1bHRfbW9kZUIICgZvYmplY3QiIAoQcmVtb3RlX3J1bGVfZmlsZRIMCgRwYXRoGAEgASgJIi8KEHJlbW90ZV9ydWxlX2h0dHASCwoDdXJsGAEgASgJEg4KBm1ldGhvZBgCIAEoCSo0CgRtb2RlEgoKBmJ5cGFzcxAAEgoKBmRpcmVjdBABEgkKBXByb3h5EAISCQoFYmxvY2sQAypfChByZXNvbHZlX3N0cmF0ZWd5EgsKB2RlZmF1bHQQABIPCgtwcmVmZXJfaXB2NBABEg0KCW9ubHlfaXB2NBACEg8KC3ByZWZlcl9pcHY2EAMSDQoJb25seV9pcHY2EAQqXQoXdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3kSIwofdWRwX3Byb3h5X2ZxZG5fc3RyYXRlZ3lfZGVmYXVsdBAAEgsKB3Jlc29sdmUQARIQCgxza2lwX3Jlc29sdmUQAkI3WjVnaXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3MvY29uZmlnL2J5cGFzc2IGcHJvdG8z");

/**
 * @generated from message yuhaiin.bypass.config
 */
export type config = Message<"yuhaiin.bypass.config"> & {
  /**
   * @generated from field: yuhaiin.bypass.mode tcp = 3;
   */
  tcp: mode;

  /**
   * @generated from field: yuhaiin.bypass.mode udp = 4;
   */
  udp: mode;

  /**
   * @generated from field: string bypass_file = 2 [json_name = "bypass_file", deprecated = true];
   * @deprecated
   */
  bypassFile: string;

  /**
   * @generated from field: yuhaiin.bypass.udp_proxy_fqdn_strategy udp_proxy_fqdn = 6 [json_name = "udp_proxy_fqdn"];
   */
  udpProxyFqdn: udp_proxy_fqdn_strategy;

  /**
   * @generated from field: repeated yuhaiin.bypass.mode_config custom_rule_v3 = 7 [json_name = "custom_rule_v3"];
   */
  customRuleV3: mode_config[];

  /**
   * @generated from field: repeated yuhaiin.bypass.remote_rule remote_rules = 8 [json_name = "remote_rules"];
   */
  remoteRules: remote_rule[];

  /**
   * resolve domain locally
   *
   * @generated from field: bool resolve_locally = 9 [json_name = "resolve_locally"];
   */
  resolveLocally: boolean;
};

/**
 * Describes the message yuhaiin.bypass.config.
 * Use `create(configSchema)` to create a new message.
 */
export const configSchema: GenMessage<config> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 0);

/**
 * @generated from message yuhaiin.bypass.mode_config
 */
export type mode_config = Message<"yuhaiin.bypass.mode_config"> & {
  /**
   * @generated from field: yuhaiin.bypass.mode mode = 1;
   */
  mode: mode;

  /**
   * @generated from field: string tag = 2;
   */
  tag: string;

  /**
   * @generated from field: repeated string hostname = 3;
   */
  hostname: string[];

  /**
   * @generated from field: yuhaiin.bypass.resolve_strategy resolve_strategy = 4 [json_name = "resolve_strategy"];
   */
  resolveStrategy: resolve_strategy;

  /**
   * @generated from field: yuhaiin.bypass.udp_proxy_fqdn_strategy udp_proxy_fqdn_strategy = 6 [json_name = "udp_proxy_fqdn_strategy"];
   */
  udpProxyFqdnStrategy: udp_proxy_fqdn_strategy;

  /**
   * @generated from field: map<string, string> error_msgs = 7 [json_name = "error_msg"];
   */
  errorMsgs: { [key: string]: string };
};

/**
 * Describes the message yuhaiin.bypass.mode_config.
 * Use `create(mode_configSchema)` to create a new message.
 */
export const mode_configSchema: GenMessage<mode_config> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 1);

/**
 * @generated from message yuhaiin.bypass.remote_rule
 */
export type remote_rule = Message<"yuhaiin.bypass.remote_rule"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from oneof yuhaiin.bypass.remote_rule.object
   */
  object: {
    /**
     * @generated from field: yuhaiin.bypass.remote_rule_file file = 3;
     */
    value: remote_rule_file;
    case: "file";
  } | {
    /**
     * @generated from field: yuhaiin.bypass.remote_rule_http http = 4;
     */
    value: remote_rule_http;
    case: "http";
  } | { case: undefined; value?: undefined };

  /**
   * error message when rules can't get from remote
   *
   * @generated from field: string error_msg = 5 [json_name = "error_msg"];
   */
  errorMsg: string;

  /**
   * @generated from field: yuhaiin.bypass.mode_config default_mode = 6 [json_name = "default_mode"];
   */
  defaultMode?: mode_config;
};

/**
 * Describes the message yuhaiin.bypass.remote_rule.
 * Use `create(remote_ruleSchema)` to create a new message.
 */
export const remote_ruleSchema: GenMessage<remote_rule> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 2);

/**
 * @generated from message yuhaiin.bypass.remote_rule_file
 */
export type remote_rule_file = Message<"yuhaiin.bypass.remote_rule_file"> & {
  /**
   * @generated from field: string path = 1;
   */
  path: string;
};

/**
 * Describes the message yuhaiin.bypass.remote_rule_file.
 * Use `create(remote_rule_fileSchema)` to create a new message.
 */
export const remote_rule_fileSchema: GenMessage<remote_rule_file> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 3);

/**
 * @generated from message yuhaiin.bypass.remote_rule_http
 */
export type remote_rule_http = Message<"yuhaiin.bypass.remote_rule_http"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * method of http request, default: GET
   *
   * @generated from field: string method = 2;
   */
  method: string;
};

/**
 * Describes the message yuhaiin.bypass.remote_rule_http.
 * Use `create(remote_rule_httpSchema)` to create a new message.
 */
export const remote_rule_httpSchema: GenMessage<remote_rule_http> = /*@__PURE__*/
  messageDesc(file_config_bypass_bypass, 4);

/**
 * @generated from enum yuhaiin.bypass.mode
 */
export enum mode {
  /**
   * @generated from enum value: bypass = 0;
   */
  bypass = 0,

  /**
   * @generated from enum value: direct = 1;
   */
  direct = 1,

  /**
   * @generated from enum value: proxy = 2;
   */
  proxy = 2,

  /**
   * @generated from enum value: block = 3;
   */
  block = 3,
}

/**
 * Describes the enum yuhaiin.bypass.mode.
 */
export const modeSchema: GenEnum<mode> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 0);

/**
 * @generated from enum yuhaiin.bypass.resolve_strategy
 */
export enum resolve_strategy {
  /**
   * @generated from enum value: default = 0;
   */
  default = 0,

  /**
   * @generated from enum value: prefer_ipv4 = 1;
   */
  prefer_ipv4 = 1,

  /**
   * @generated from enum value: only_ipv4 = 2;
   */
  only_ipv4 = 2,

  /**
   * @generated from enum value: prefer_ipv6 = 3;
   */
  prefer_ipv6 = 3,

  /**
   * @generated from enum value: only_ipv6 = 4;
   */
  only_ipv6 = 4,
}

/**
 * Describes the enum yuhaiin.bypass.resolve_strategy.
 */
export const resolve_strategySchema: GenEnum<resolve_strategy> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 1);

/**
 * @generated from enum yuhaiin.bypass.udp_proxy_fqdn_strategy
 */
export enum udp_proxy_fqdn_strategy {
  /**
   * @generated from enum value: udp_proxy_fqdn_strategy_default = 0;
   */
  udp_proxy_fqdn_strategy_default = 0,

  /**
   * @generated from enum value: resolve = 1;
   */
  resolve = 1,

  /**
   * @generated from enum value: skip_resolve = 2;
   */
  skip_resolve = 2,
}

/**
 * Describes the enum yuhaiin.bypass.udp_proxy_fqdn_strategy.
 */
export const udp_proxy_fqdn_strategySchema: GenEnum<udp_proxy_fqdn_strategy> = /*@__PURE__*/
  enumDesc(file_config_bypass_bypass, 2);

