// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file config/config.proto (package yuhaiin.config, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { logcat } from "./log/log_pb";
import { file_config_log_log } from "./log/log_pb";
import type { config } from "./bypass/bypass_pb";
import { file_config_bypass_bypass } from "./bypass/bypass_pb";
import type { dns_config } from "./dns/dns_pb";
import { file_config_dns_dns } from "./dns/dns_pb";
import type { inbound_config } from "./listener/listener_pb";
import { file_config_listener_listener } from "./listener/listener_pb";
import { file_google_protobuf_go_features } from "../google/protobuf/go_features_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/config.proto.
 */
export const file_config_config: GenFile = /*@__PURE__*/
  fileDesc("ChNjb25maWcvY29uZmlnLnByb3RvEg55dWhhaWluLmNvbmZpZyLhBAoHc2V0dGluZxIMCgRpcHY2GAcgASgIEkYKHmlwdjZfbG9jYWxfYWRkcl9wcmVmZXJfdW5pY2FzdBgKIAEoCFIeaXB2Nl9sb2NhbF9hZGRyX3ByZWZlcl91bmljYXN0EjQKFXVzZV9kZWZhdWx0X2ludGVyZmFjZRgNIAEoCFIVdXNlX2RlZmF1bHRfaW50ZXJmYWNlEiQKDW5ldF9pbnRlcmZhY2UYBiABKAlSDW5ldF9pbnRlcmZhY2USQAoMc3lzdGVtX3Byb3h5GAEgASgLMhwueXVoYWlpbi5jb25maWcuc3lzdGVtX3Byb3h5UgxzeXN0ZW1fcHJveHkSJgoGYnlwYXNzGAIgASgLMhYueXVoYWlpbi5ieXBhc3MuY29uZmlnEiQKA2RucxgEIAEoCzIXLnl1aGFpaW4uZG5zLmRuc19jb25maWcSMAoGc2VydmVyGAUgASgLMiAueXVoYWlpbi5saXN0ZW5lci5pbmJvdW5kX2NvbmZpZxIjCgZsb2djYXQYCCABKAsyEy55dWhhaWluLmxvZy5sb2djYXQSRgoOY29uZmlnX3ZlcnNpb24YCSABKAsyHi55dWhhaWluLmNvbmZpZy5jb25maWdfdmVyc2lvblIOY29uZmlnX3ZlcnNpb24SKgoIcGxhdGZvcm0YCyABKAsyGC55dWhhaWluLmNvbmZpZy5wbGF0Zm9ybRJJCg9hZHZhbmNlZF9jb25maWcYDCABKAsyHy55dWhhaWluLmNvbmZpZy5hZHZhbmNlZF9jb25maWdSD2FkdmFuY2VkX2NvbmZpZyJpCg9hZHZhbmNlZF9jb25maWcSKAoPdWRwX2J1ZmZlcl9zaXplGAEgASgFUg91ZHBfYnVmZmVyX3NpemUSLAoRcmVsYXlfYnVmZmVyX3NpemUYAiABKAVSEXJlbGF5X2J1ZmZlcl9zaXplIiwKDHN5c3RlbV9wcm94eRIMCgRodHRwGAIgASgIEg4KBnNvY2tzNRgDIAEoCCK0AQoEaW5mbxIPCgd2ZXJzaW9uGAEgASgJEg4KBmNvbW1pdBgCIAEoCRIeCgpidWlsZF90aW1lGAMgASgJUgpidWlsZF90aW1lEh4KCmdvX3ZlcnNpb24YBCABKAlSCmdvX3ZlcnNpb24SDAoEYXJjaBgFIAEoCRIQCghwbGF0Zm9ybRgGIAEoCRIKCgJvcxgHIAEoCRIQCghjb21waWxlchgIIAEoCRINCgVidWlsZBgJIAMoCSIhCg5jb25maWdfdmVyc2lvbhIPCgd2ZXJzaW9uGAEgASgEIiwKCHBsYXRmb3JtEiAKC2FuZHJvaWRfYXBwGAEgASgIUgthbmRyb2lkX2FwcEI4Wi5naXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3MvY29uZmlnkgMF0j4CEANiCGVkaXRpb25zcOgH", [file_config_log_log, file_config_bypass_bypass, file_config_dns_dns, file_config_listener_listener, file_google_protobuf_go_features]);

/**
 * @generated from message yuhaiin.config.setting
 */
export type setting = Message<"yuhaiin.config.setting"> & {
  /**
   * @generated from field: bool ipv6 = 7;
   */
  ipv6: boolean;

  /**
   * @generated from field: bool ipv6_local_addr_prefer_unicast = 10 [json_name = "ipv6_local_addr_prefer_unicast"];
   */
  ipv6LocalAddrPreferUnicast: boolean;

  /**
   * @generated from field: bool use_default_interface = 13 [json_name = "use_default_interface"];
   */
  useDefaultInterface: boolean;

  /**
   * net_interface, eg: eth0
   *
   * @generated from field: string net_interface = 6 [json_name = "net_interface"];
   */
  netInterface: string;

  /**
   * @generated from field: yuhaiin.config.system_proxy system_proxy = 1 [json_name = "system_proxy"];
   */
  systemProxy?: system_proxy;

  /**
   * @generated from field: yuhaiin.bypass.config bypass = 2;
   */
  bypass?: config;

  /**
   * @generated from field: yuhaiin.dns.dns_config dns = 4;
   */
  dns?: dns_config;

  /**
   * @generated from field: yuhaiin.listener.inbound_config server = 5;
   */
  server?: inbound_config;

  /**
   * @generated from field: yuhaiin.log.logcat logcat = 8;
   */
  logcat?: logcat;

  /**
   * @generated from field: yuhaiin.config.config_version config_version = 9 [json_name = "config_version"];
   */
  configVersion?: config_version;

  /**
   * @generated from field: yuhaiin.config.platform platform = 11;
   */
  platform?: platform;

  /**
   * @generated from field: yuhaiin.config.advanced_config advanced_config = 12 [json_name = "advanced_config"];
   */
  advancedConfig?: advanced_config;
};

/**
 * Describes the message yuhaiin.config.setting.
 * Use `create(settingSchema)` to create a new message.
 */
export const settingSchema: GenMessage<setting> = /*@__PURE__*/
  messageDesc(file_config_config, 0);

/**
 * @generated from message yuhaiin.config.advanced_config
 */
export type advanced_config = Message<"yuhaiin.config.advanced_config"> & {
  /**
   * @generated from field: int32 udp_buffer_size = 1 [json_name = "udp_buffer_size"];
   */
  udpBufferSize: number;

  /**
   * @generated from field: int32 relay_buffer_size = 2 [json_name = "relay_buffer_size"];
   */
  relayBufferSize: number;
};

/**
 * Describes the message yuhaiin.config.advanced_config.
 * Use `create(advanced_configSchema)` to create a new message.
 */
export const advanced_configSchema: GenMessage<advanced_config> = /*@__PURE__*/
  messageDesc(file_config_config, 1);

/**
 * @generated from message yuhaiin.config.system_proxy
 */
export type system_proxy = Message<"yuhaiin.config.system_proxy"> & {
  /**
   * @generated from field: bool http = 2;
   */
  http: boolean;

  /**
   * @generated from field: bool socks5 = 3;
   */
  socks5: boolean;
};

/**
 * Describes the message yuhaiin.config.system_proxy.
 * Use `create(system_proxySchema)` to create a new message.
 */
export const system_proxySchema: GenMessage<system_proxy> = /*@__PURE__*/
  messageDesc(file_config_config, 2);

/**
 * @generated from message yuhaiin.config.info
 */
export type info = Message<"yuhaiin.config.info"> & {
  /**
   * @generated from field: string version = 1;
   */
  version: string;

  /**
   * @generated from field: string commit = 2;
   */
  commit: string;

  /**
   * @generated from field: string build_time = 3 [json_name = "build_time"];
   */
  buildTime: string;

  /**
   * @generated from field: string go_version = 4 [json_name = "go_version"];
   */
  goVersion: string;

  /**
   * @generated from field: string arch = 5;
   */
  arch: string;

  /**
   * @generated from field: string platform = 6;
   */
  platform: string;

  /**
   * @generated from field: string os = 7;
   */
  os: string;

  /**
   * @generated from field: string compiler = 8;
   */
  compiler: string;

  /**
   * @generated from field: repeated string build = 9;
   */
  build: string[];
};

/**
 * Describes the message yuhaiin.config.info.
 * Use `create(infoSchema)` to create a new message.
 */
export const infoSchema: GenMessage<info> = /*@__PURE__*/
  messageDesc(file_config_config, 3);

/**
 * @generated from message yuhaiin.config.config_version
 */
export type config_version = Message<"yuhaiin.config.config_version"> & {
  /**
   * @generated from field: uint64 version = 1;
   */
  version: bigint;
};

/**
 * Describes the message yuhaiin.config.config_version.
 * Use `create(config_versionSchema)` to create a new message.
 */
export const config_versionSchema: GenMessage<config_version> = /*@__PURE__*/
  messageDesc(file_config_config, 4);

/**
 * @generated from message yuhaiin.config.platform
 */
export type platform = Message<"yuhaiin.config.platform"> & {
  /**
   * @generated from field: bool android_app = 1 [json_name = "android_app"];
   */
  androidApp: boolean;
};

/**
 * Describes the message yuhaiin.config.platform.
 * Use `create(platformSchema)` to create a new message.
 */
export const platformSchema: GenMessage<platform> = /*@__PURE__*/
  messageDesc(file_config_config, 5);

