// @generated by protoc-gen-es v2.10.0 with parameter "target=ts"
// @generated from file config/dns.proto (package yuhaiin.dns, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_go_features } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/dns.proto.
 */
export const file_config_dns: GenFile = /*@__PURE__*/
  fileDesc("ChBjb25maWcvZG5zLnByb3RvEgt5dWhhaWluLmRucyJsCgNkbnMSDAoEaG9zdBgBIAEoCRIfCgR0eXBlGAUgASgOMhEueXVoYWlpbi5kbnMudHlwZRIOCgZzdWJuZXQYBCABKAkSJgoOdGxzX3NlcnZlcm5hbWUYAiABKAlSDnRsc19zZXJ2ZXJuYW1lIpYECgpkbnNfY29uZmlnEg4KBnNlcnZlchgEIAEoCRIPCgdmYWtlZG5zGAUgASgIEioKEGZha2VkbnNfaXBfcmFuZ2UYBiABKAlSEGZha2VkbnNfaXBfcmFuZ2USLgoSZmFrZWRuc19pcHY2X3JhbmdlGA0gASgJUhJmYWtlZG5zX2lwdjZfcmFuZ2USLAoRZmFrZWRuc193aGl0ZWxpc3QYCSADKAlSEWZha2VkbnNfd2hpdGVsaXN0EjgKF2Zha2VkbnNfc2tpcF9jaGVja19saXN0GA4gAygJUhdmYWtlZG5zX3NraXBfY2hlY2tfbGlzdBIxCgVob3N0cxgIIAMoCzIiLnl1aGFpaW4uZG5zLmRuc19jb25maWcuSG9zdHNFbnRyeRI3CghyZXNvbHZlchgKIAMoCzIlLnl1aGFpaW4uZG5zLmRuc19jb25maWcuUmVzb2x2ZXJFbnRyeRosCgpIb3N0c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaQQoNUmVzb2x2ZXJFbnRyeRILCgNrZXkYASABKAkSHwoFdmFsdWUYAiABKAsyEC55dWhhaWluLmRucy5kbnM6AjgBSgQIBxAISgQIARACSgQIAhADSgQIAxAEUhRyZXNvbHZlX3JlbW90ZV9kb21haVIFbG9jYWxSBnJlbW90ZVIJYm9vdHN0cmFwIp4BCg5mYWtlZG5zX2NvbmZpZxIPCgdlbmFibGVkGAEgASgIEh4KCmlwdjRfcmFuZ2UYAiABKAlSCmlwdjRfcmFuZ2USHgoKaXB2Nl9yYW5nZRgDIAEoCVIKaXB2Nl9yYW5nZRIRCgl3aGl0ZWxpc3QYBCADKAkSKAoPc2tpcF9jaGVja19saXN0GAUgAygJUg9za2lwX2NoZWNrX2xpc3QiFgoGc2VydmVyEgwKBGhvc3QYASABKAkixQIKDWRuc19jb25maWdfdjISIwoGc2VydmVyGAEgASgLMhMueXVoYWlpbi5kbnMuc2VydmVyEiwKB2Zha2VkbnMYAiABKAsyGy55dWhhaWluLmRucy5mYWtlZG5zX2NvbmZpZxI0CgVob3N0cxgDIAMoCzIlLnl1aGFpaW4uZG5zLmRuc19jb25maWdfdjIuSG9zdHNFbnRyeRI6CghyZXNvbHZlchgEIAMoCzIoLnl1aGFpaW4uZG5zLmRuc19jb25maWdfdjIuUmVzb2x2ZXJFbnRyeRosCgpIb3N0c0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEaQQoNUmVzb2x2ZXJFbnRyeRILCgNrZXkYASABKAkSHwoFdmFsdWUYAiABKAsyEC55dWhhaWluLmRucy5kbnM6AjgBKkoKBHR5cGUSCwoHcmVzZXJ2ZRAAEgcKA3VkcBABEgcKA3RjcBACEgcKA2RvaBADEgcKA2RvdBAEEgcKA2RvcRAFEggKBGRvaDMQBkI4Wi5naXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3MvY29uZmlnkgMF0j4CEANiCGVkaXRpb25zcOgH", [file_google_protobuf_go_features]);

/**
 * @generated from message yuhaiin.dns.dns
 */
export type dns = Message<"yuhaiin.dns.dns"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;

  /**
   * @generated from field: yuhaiin.dns.type type = 5;
   */
  type: type;

  /**
   * @generated from field: string subnet = 4;
   */
  subnet: string;

  /**
   * @generated from field: string tls_servername = 2 [json_name = "tls_servername"];
   */
  tlsServername: string;
};

/**
 * Describes the message yuhaiin.dns.dns.
 * Use `create(dnsSchema)` to create a new message.
 */
export const dnsSchema: GenMessage<dns> = /*@__PURE__*/
  messageDesc(file_config_dns, 0);

/**
 * @generated from message yuhaiin.dns.dns_config
 */
export type dns_config = Message<"yuhaiin.dns.dns_config"> & {
  /**
   * @generated from field: string server = 4;
   */
  server: string;

  /**
   * @generated from field: bool fakedns = 5;
   */
  fakedns: boolean;

  /**
   * @generated from field: string fakedns_ip_range = 6 [json_name = "fakedns_ip_range"];
   */
  fakednsIpRange: string;

  /**
   * @generated from field: string fakedns_ipv6_range = 13 [json_name = "fakedns_ipv6_range"];
   */
  fakednsIpv6Range: string;

  /**
   * @generated from field: repeated string fakedns_whitelist = 9 [json_name = "fakedns_whitelist"];
   */
  fakednsWhitelist: string[];

  /**
   * @generated from field: repeated string fakedns_skip_check_list = 14 [json_name = "fakedns_skip_check_list"];
   */
  fakednsSkipCheckList: string[];

  /**
   * @generated from field: map<string, string> hosts = 8;
   */
  hosts: { [key: string]: string };

  /**
   * @generated from field: map<string, yuhaiin.dns.dns> resolver = 10;
   */
  resolver: { [key: string]: dns };
};

/**
 * Describes the message yuhaiin.dns.dns_config.
 * Use `create(dns_configSchema)` to create a new message.
 */
export const dns_configSchema: GenMessage<dns_config> = /*@__PURE__*/
  messageDesc(file_config_dns, 1);

/**
 * @generated from message yuhaiin.dns.fakedns_config
 */
export type fakedns_config = Message<"yuhaiin.dns.fakedns_config"> & {
  /**
   * @generated from field: bool enabled = 1;
   */
  enabled: boolean;

  /**
   * @generated from field: string ipv4_range = 2 [json_name = "ipv4_range"];
   */
  ipv4Range: string;

  /**
   * @generated from field: string ipv6_range = 3 [json_name = "ipv6_range"];
   */
  ipv6Range: string;

  /**
   * @generated from field: repeated string whitelist = 4;
   */
  whitelist: string[];

  /**
   * @generated from field: repeated string skip_check_list = 5 [json_name = "skip_check_list"];
   */
  skipCheckList: string[];
};

/**
 * Describes the message yuhaiin.dns.fakedns_config.
 * Use `create(fakedns_configSchema)` to create a new message.
 */
export const fakedns_configSchema: GenMessage<fakedns_config> = /*@__PURE__*/
  messageDesc(file_config_dns, 2);

/**
 * @generated from message yuhaiin.dns.server
 */
export type server = Message<"yuhaiin.dns.server"> & {
  /**
   * @generated from field: string host = 1;
   */
  host: string;
};

/**
 * Describes the message yuhaiin.dns.server.
 * Use `create(serverSchema)` to create a new message.
 */
export const serverSchema: GenMessage<server> = /*@__PURE__*/
  messageDesc(file_config_dns, 3);

/**
 * @generated from message yuhaiin.dns.dns_config_v2
 */
export type dns_config_v2 = Message<"yuhaiin.dns.dns_config_v2"> & {
  /**
   * @generated from field: yuhaiin.dns.server server = 1;
   */
  server?: server;

  /**
   * @generated from field: yuhaiin.dns.fakedns_config fakedns = 2;
   */
  fakedns?: fakedns_config;

  /**
   * @generated from field: map<string, string> hosts = 3;
   */
  hosts: { [key: string]: string };

  /**
   * @generated from field: map<string, yuhaiin.dns.dns> resolver = 4;
   */
  resolver: { [key: string]: dns };
};

/**
 * Describes the message yuhaiin.dns.dns_config_v2.
 * Use `create(dns_config_v2Schema)` to create a new message.
 */
export const dns_config_v2Schema: GenMessage<dns_config_v2> = /*@__PURE__*/
  messageDesc(file_config_dns, 4);

/**
 * @generated from enum yuhaiin.dns.type
 */
export enum type {
  /**
   * @generated from enum value: reserve = 0;
   */
  reserve = 0,

  /**
   * @generated from enum value: udp = 1;
   */
  udp = 1,

  /**
   * @generated from enum value: tcp = 2;
   */
  tcp = 2,

  /**
   * @generated from enum value: doh = 3;
   */
  doh = 3,

  /**
   * @generated from enum value: dot = 4;
   */
  dot = 4,

  /**
   * @generated from enum value: doq = 5;
   */
  doq = 5,

  /**
   * @generated from enum value: doh3 = 6;
   */
  doh3 = 6,
}

/**
 * Describes the enum yuhaiin.dns.type.
 */
export const typeSchema: GenEnum<type> = /*@__PURE__*/
  enumDesc(file_config_dns, 0);

