// @generated by protoc-gen-es v2.10.2 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file node/subscribe.proto (package yuhaiin.subscribe, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_go_features } from "@bufbuild/protobuf/wkt";
import type { point } from "./point_pb";
import { file_node_point } from "./point_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file node/subscribe.proto.
 */
export const file_node_subscribe: GenFile = /*@__PURE__*/
  fileDesc("ChRub2RlL3N1YnNjcmliZS5wcm90bxIReXVoYWlpbi5zdWJzY3JpYmUiSAoEbGluaxIMCgRuYW1lGAEgASgJEiUKBHR5cGUYAiABKA4yFy55dWhhaWluLnN1YnNjcmliZS50eXBlEgsKA3VybBgDIAEoCSJqCgdQdWJsaXNoEg4KBnBvaW50cxgBIAMoCRIMCgRwYXRoGAIgASgJEgwKBG5hbWUYAyABKAkSEAoIcGFzc3dvcmQYBCABKAkSDwoHYWRkcmVzcxgFIAEoCRIQCghpbnNlY3VyZRgGIAEoCCL4AQoKWXVoYWlpblVybBI2CgZyZW1vdGUYASABKAsyJC55dWhhaWluLnN1YnNjcmliZS5ZdWhhaWluVXJsLlJlbW90ZUgAEjYKBnBvaW50cxgCIAEoCzIkLnl1aGFpaW4uc3Vic2NyaWJlLll1aGFpaW5VcmwuUG9pbnRzSAASDAoEbmFtZRgDIAEoCRo1CgZSZW1vdGUSKwoHcHVibGlzaBgBIAEoCzIaLnl1aGFpaW4uc3Vic2NyaWJlLlB1Ymxpc2gaLgoGUG9pbnRzEiQKBnBvaW50cxgBIAMoCzIULnl1aGFpaW4ucG9pbnQucG9pbnRCBQoDdXJsKk0KBHR5cGUSCwoHcmVzZXJ2ZRAAEgoKBnRyb2phbhABEgkKBXZtZXNzEAISDwoLc2hhZG93c29ja3MQAxIQCgxzaGFkb3dzb2Nrc3IQBEI2WixnaXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3Mvbm9kZZIDBdI+AhADYghlZGl0aW9uc3DoBw", [file_google_protobuf_go_features, file_node_point]);

/**
 * @generated from message yuhaiin.subscribe.link
 */
export type link = Message<"yuhaiin.subscribe.link"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: yuhaiin.subscribe.type type = 2;
   */
  type: type;

  /**
   * @generated from field: string url = 3;
   */
  url: string;
};

/**
 * Describes the message yuhaiin.subscribe.link.
 * Use `create(linkSchema)` to create a new message.
 */
export const linkSchema: GenMessage<link> = /*@__PURE__*/
  messageDesc(file_node_subscribe, 0);

/**
 * @generated from message yuhaiin.subscribe.Publish
 */
export type Publish = Message<"yuhaiin.subscribe.Publish"> & {
  /**
   * @generated from field: repeated string points = 1;
   */
  points: string[];

  /**
   * @generated from field: string path = 2;
   */
  path: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: string address = 5;
   */
  address: string;

  /**
   * @generated from field: bool insecure = 6;
   */
  insecure: boolean;
};

/**
 * Describes the message yuhaiin.subscribe.Publish.
 * Use `create(PublishSchema)` to create a new message.
 */
export const PublishSchema: GenMessage<Publish> = /*@__PURE__*/
  messageDesc(file_node_subscribe, 1);

/**
 * @generated from message yuhaiin.subscribe.YuhaiinUrl
 */
export type YuhaiinUrl = Message<"yuhaiin.subscribe.YuhaiinUrl"> & {
  /**
   * @generated from oneof yuhaiin.subscribe.YuhaiinUrl.url
   */
  url: {
    /**
     * @generated from field: yuhaiin.subscribe.YuhaiinUrl.Remote remote = 1;
     */
    value: YuhaiinUrl_Remote;
    case: "remote";
  } | {
    /**
     * @generated from field: yuhaiin.subscribe.YuhaiinUrl.Points points = 2;
     */
    value: YuhaiinUrl_Points;
    case: "points";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: string name = 3;
   */
  name: string;
};

/**
 * Describes the message yuhaiin.subscribe.YuhaiinUrl.
 * Use `create(YuhaiinUrlSchema)` to create a new message.
 */
export const YuhaiinUrlSchema: GenMessage<YuhaiinUrl> = /*@__PURE__*/
  messageDesc(file_node_subscribe, 2);

/**
 * @generated from message yuhaiin.subscribe.YuhaiinUrl.Remote
 */
export type YuhaiinUrl_Remote = Message<"yuhaiin.subscribe.YuhaiinUrl.Remote"> & {
  /**
   * @generated from field: yuhaiin.subscribe.Publish publish = 1;
   */
  publish?: Publish;
};

/**
 * Describes the message yuhaiin.subscribe.YuhaiinUrl.Remote.
 * Use `create(YuhaiinUrl_RemoteSchema)` to create a new message.
 */
export const YuhaiinUrl_RemoteSchema: GenMessage<YuhaiinUrl_Remote> = /*@__PURE__*/
  messageDesc(file_node_subscribe, 2, 0);

/**
 * @generated from message yuhaiin.subscribe.YuhaiinUrl.Points
 */
export type YuhaiinUrl_Points = Message<"yuhaiin.subscribe.YuhaiinUrl.Points"> & {
  /**
   * @generated from field: repeated yuhaiin.point.point points = 1;
   */
  points: point[];
};

/**
 * Describes the message yuhaiin.subscribe.YuhaiinUrl.Points.
 * Use `create(YuhaiinUrl_PointsSchema)` to create a new message.
 */
export const YuhaiinUrl_PointsSchema: GenMessage<YuhaiinUrl_Points> = /*@__PURE__*/
  messageDesc(file_node_subscribe, 2, 1);

/**
 * @generated from enum yuhaiin.subscribe.type
 */
export enum type {
  /**
   * @generated from enum value: reserve = 0;
   */
  reserve = 0,

  /**
   * @generated from enum value: trojan = 1;
   */
  trojan = 1,

  /**
   * @generated from enum value: vmess = 2;
   */
  vmess = 2,

  /**
   * @generated from enum value: shadowsocks = 3;
   */
  shadowsocks = 3,

  /**
   * @generated from enum value: shadowsocksr = 4;
   */
  shadowsocksr = 4,
}

/**
 * Describes the enum yuhaiin.subscribe.type.
 */
export const typeSchema: GenEnum<type> = /*@__PURE__*/
  enumDesc(file_node_subscribe, 0);

