// @generated by protoc-gen-es v2.2.0 with parameter "target=ts"
// @generated from file config/grpc/config.proto (package yuhaiin.protos.config.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { infoSchema, settingSchema } from "../config_pb";
import { file_config_config } from "../config_pb";
import type { configSchema, mode_config } from "../bypass/bypass_pb";
import { file_config_bypass_bypass } from "../bypass/bypass_pb";
import type { EmptySchema, StringValueSchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config/grpc/config.proto.
 */
export const file_config_grpc_config: GenFile = /*@__PURE__*/
  fileDesc("Chhjb25maWcvZ3JwYy9jb25maWcucHJvdG8SHXl1aGFpaW4ucHJvdG9zLmNvbmZpZy5zZXJ2aWNlImoKDXRlc3RfcmVzcG9uc2USKQoEbW9kZRgBIAEoCzIbLnl1aGFpaW4uYnlwYXNzLm1vZGVfY29uZmlnEg4KBnJlYXNvbhgCIAEoCRIeCgphZnRlcl9hZGRyGAMgASgJUgphZnRlcl9hZGRyIowBCg1ibG9ja19oaXN0b3J5EhAKCHByb3RvY29sGAEgASgJEgwKBGhvc3QYAiABKAkSKAoEdGltZRgDIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASDwoHcHJvY2VzcxgEIAEoCRIgCgtibG9ja19jb3VudBgFIAEoBFILYmxvY2tfY291bnQihwEKEmJsb2NrX2hpc3RvcnlfbGlzdBI9CgdvYmplY3RzGAEgAygLMiwueXVoYWlpbi5wcm90b3MuY29uZmlnLnNlcnZpY2UuYmxvY2tfaGlzdG9yeRIyChRkdW1wX3Byb2Nlc3NfZW5hYmxlZBgCIAEoCFIUZHVtcF9wcm9jZXNzX2VuYWJsZWQyuAEKDmNvbmZpZ19zZXJ2aWNlEjcKBGxvYWQSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFy55dWhhaWluLmNvbmZpZy5zZXR0aW5nEjcKBHNhdmUSFy55dWhhaWluLmNvbmZpZy5zZXR0aW5nGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EjQKBGluZm8SFi5nb29nbGUucHJvdG9idWYuRW1wdHkaFC55dWhhaWluLmNvbmZpZy5pbmZvMuICCgZieXBhc3MSNgoEbG9hZBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLnl1aGFpaW4uYnlwYXNzLmNvbmZpZxI2CgRzYXZlEhYueXVoYWlpbi5ieXBhc3MuY29uZmlnGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EjgKBnJlbG9hZBIWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRoWLmdvb2dsZS5wcm90b2J1Zi5FbXB0eRJSCgR0ZXN0EhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlGiwueXVoYWlpbi5wcm90b3MuY29uZmlnLnNlcnZpY2UudGVzdF9yZXNwb25zZRJaCg1ibG9ja19oaXN0b3J5EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjEueXVoYWlpbi5wcm90b3MuY29uZmlnLnNlcnZpY2UuYmxvY2tfaGlzdG9yeV9saXN0QjhaNmdpdGh1Yi5jb20vQXN1dG9ydWZhL3l1aGFpaW4vcGtnL3Byb3Rvcy9jb25maWcvc2VydmljZWIGcHJvdG8z", [file_config_config, file_config_bypass_bypass, file_google_protobuf_empty, file_google_protobuf_wrappers, file_google_protobuf_timestamp]);

/**
 * @generated from message yuhaiin.protos.config.service.test_response
 */
export type test_response = Message<"yuhaiin.protos.config.service.test_response"> & {
  /**
   * @generated from field: yuhaiin.bypass.mode_config mode = 1;
   */
  mode?: mode_config;

  /**
   * @generated from field: string reason = 2;
   */
  reason: string;

  /**
   * @generated from field: string after_addr = 3 [json_name = "after_addr"];
   */
  afterAddr: string;
};

/**
 * Describes the message yuhaiin.protos.config.service.test_response.
 * Use `create(test_responseSchema)` to create a new message.
 */
export const test_responseSchema: GenMessage<test_response> = /*@__PURE__*/
  messageDesc(file_config_grpc_config, 0);

/**
 * @generated from message yuhaiin.protos.config.service.block_history
 */
export type block_history = Message<"yuhaiin.protos.config.service.block_history"> & {
  /**
   * @generated from field: string protocol = 1;
   */
  protocol: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: google.protobuf.Timestamp time = 3;
   */
  time?: Timestamp;

  /**
   * @generated from field: string process = 4;
   */
  process: string;

  /**
   * @generated from field: uint64 block_count = 5 [json_name = "block_count"];
   */
  blockCount: bigint;
};

/**
 * Describes the message yuhaiin.protos.config.service.block_history.
 * Use `create(block_historySchema)` to create a new message.
 */
export const block_historySchema: GenMessage<block_history> = /*@__PURE__*/
  messageDesc(file_config_grpc_config, 1);

/**
 * @generated from message yuhaiin.protos.config.service.block_history_list
 */
export type block_history_list = Message<"yuhaiin.protos.config.service.block_history_list"> & {
  /**
   * @generated from field: repeated yuhaiin.protos.config.service.block_history objects = 1;
   */
  objects: block_history[];

  /**
   * @generated from field: bool dump_process_enabled = 2 [json_name = "dump_process_enabled"];
   */
  dumpProcessEnabled: boolean;
};

/**
 * Describes the message yuhaiin.protos.config.service.block_history_list.
 * Use `create(block_history_listSchema)` to create a new message.
 */
export const block_history_listSchema: GenMessage<block_history_list> = /*@__PURE__*/
  messageDesc(file_config_grpc_config, 2);

/**
 * @generated from service yuhaiin.protos.config.service.config_service
 */
export const config_service: GenService<{
  /**
   * @generated from rpc yuhaiin.protos.config.service.config_service.load
   */
  load: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof settingSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.config_service.save
   */
  save: {
    methodKind: "unary";
    input: typeof settingSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.config_service.info
   */
  info: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof infoSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_config_grpc_config, 0);

/**
 * @generated from service yuhaiin.protos.config.service.bypass
 */
export const bypass: GenService<{
  /**
   * @generated from rpc yuhaiin.protos.config.service.bypass.load
   */
  load: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof configSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.bypass.save
   */
  save: {
    methodKind: "unary";
    input: typeof configSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.bypass.reload
   */
  reload: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.bypass.test
   */
  test: {
    methodKind: "unary";
    input: typeof StringValueSchema;
    output: typeof test_responseSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.config.service.bypass.block_history
   */
  block_history: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof block_history_listSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_config_grpc_config, 1);

