// @generated by protoc-gen-es v2.10.2 with parameter "target=ts"
// @generated from file backup/backup.proto (package yuhaiin.backup, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_google_protobuf_go_features } from "@bufbuild/protobuf/wkt";
import type { point } from "../node/point_pb";
import { file_node_point } from "../node/point_pb";
import type { link } from "../node/subscribe_pb";
import { file_node_subscribe } from "../node/subscribe_pb";
import type { tags as tags$1 } from "../node/tag_pb";
import { file_node_tag } from "../node/tag_pb";
import type { dns_config_v2 } from "../config/dns_pb";
import { file_config_dns } from "../config/dns_pb";
import type { inbound_config } from "../config/inbound_pb";
import { file_config_inbound } from "../config/inbound_pb";
import type { configv2, list, rulev2 } from "../config/bypass_pb";
import { file_config_bypass } from "../config/bypass_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file backup/backup.proto.
 */
export const file_backup_backup: GenFile = /*@__PURE__*/
  fileDesc("ChNiYWNrdXAvYmFja3VwLnByb3RvEg55dWhhaWluLmJhY2t1cCJ8CgVub2RlcxIvCgVub2RlcxgBIAMoCzIgLnl1aGFpaW4uYmFja3VwLm5vZGVzLk5vZGVzRW50cnkaQgoKTm9kZXNFbnRyeRILCgNrZXkYASABKAkSIwoFdmFsdWUYAiABKAsyFC55dWhhaWluLnBvaW50LnBvaW50OgI4ASKJAQoKc3Vic2NyaWJlcxI0CgVsaW5rcxgBIAMoCzIlLnl1aGFpaW4uYmFja3VwLnN1YnNjcmliZXMuTGlua3NFbnRyeRpFCgpMaW5rc0VudHJ5EgsKA2tleRgBIAEoCRImCgV2YWx1ZRgCIAEoCzIXLnl1aGFpaW4uc3Vic2NyaWJlLmxpbms6AjgBIs0BCgVydWxlcxIoCgZjb25maWcYASABKAsyGC55dWhhaWluLmJ5cGFzcy5jb25maWd2MhIlCgVydWxlcxgCIAMoCzIWLnl1aGFpaW4uYnlwYXNzLnJ1bGV2MhIvCgVsaXN0cxgDIAMoCzIgLnl1aGFpaW4uYmFja3VwLnJ1bGVzLkxpc3RzRW50cnkaQgoKTGlzdHNFbnRyeRILCgNrZXkYASABKAkSIwoFdmFsdWUYAiABKAsyFC55dWhhaWluLmJ5cGFzcy5saXN0OgI4ASJ0CgR0YWdzEiwKBHRhZ3MYASADKAsyHi55dWhhaWluLmJhY2t1cC50YWdzLlRhZ3NFbnRyeRo+CglUYWdzRW50cnkSCwoDa2V5GAEgASgJEiAKBXZhbHVlGAIgASgLMhEueXVoYWlpbi50YWcudGFnczoCOAEikQIKDmJhY2t1cF9jb250ZW50EiQKBW5vZGVzGAIgASgLMhUueXVoYWlpbi5iYWNrdXAubm9kZXMSLgoKc3Vic2NyaWJlcxgDIAEoCzIaLnl1aGFpaW4uYmFja3VwLnN1YnNjcmliZXMSJwoDZG5zGAQgASgLMhoueXVoYWlpbi5kbnMuZG5zX2NvbmZpZ192MhIxCghpbmJvdW5kcxgFIAEoCzIfLnl1aGFpaW4uaW5ib3VuZC5pbmJvdW5kX2NvbmZpZxIkCgVydWxlcxgGIAEoCzIVLnl1aGFpaW4uYmFja3VwLnJ1bGVzEicKBHRhZ3MYByABKAsyFC55dWhhaWluLmJhY2t1cC50YWdzUgN0YWci8QEKDnJlc3RvcmVfb3B0aW9uEgsKA2FsbBgBIAEoCBINCgVydWxlcxgCIAEoCBINCgVsaXN0cxgDIAEoCBINCgVub2RlcxgEIAEoCBIMCgR0YWdzGAUgASgIEgsKA2RucxgGIAEoCBIQCghpbmJvdW5kcxgHIAEoCBISCgpzdWJzY3JpYmVzGAggASgIEj0KBnNvdXJjZRgJIAEoDjItLnl1aGFpaW4uYmFja3VwLnJlc3RvcmVfb3B0aW9uLnJlc3RvcmVfc291cmNlIiUKDnJlc3RvcmVfc291cmNlEgsKB3Vua25vd24QABIGCgJzMxABQjhaLmdpdGh1Yi5jb20vQXN1dG9ydWZhL3l1aGFpaW4vcGtnL3Byb3Rvcy9iYWNrdXCSAwXSPgIQA2IIZWRpdGlvbnNw6Ac", [file_google_protobuf_go_features, file_node_point, file_node_subscribe, file_node_tag, file_config_dns, file_config_inbound, file_config_bypass]);

/**
 * @generated from message yuhaiin.backup.nodes
 */
export type nodes = Message<"yuhaiin.backup.nodes"> & {
  /**
   * @generated from field: map<string, yuhaiin.point.point> nodes = 1;
   */
  nodes: { [key: string]: point };
};

/**
 * Describes the message yuhaiin.backup.nodes.
 * Use `create(nodesSchema)` to create a new message.
 */
export const nodesSchema: GenMessage<nodes> = /*@__PURE__*/
  messageDesc(file_backup_backup, 0);

/**
 * @generated from message yuhaiin.backup.subscribes
 */
export type subscribes = Message<"yuhaiin.backup.subscribes"> & {
  /**
   * @generated from field: map<string, yuhaiin.subscribe.link> links = 1;
   */
  links: { [key: string]: link };
};

/**
 * Describes the message yuhaiin.backup.subscribes.
 * Use `create(subscribesSchema)` to create a new message.
 */
export const subscribesSchema: GenMessage<subscribes> = /*@__PURE__*/
  messageDesc(file_backup_backup, 1);

/**
 * @generated from message yuhaiin.backup.rules
 */
export type rules = Message<"yuhaiin.backup.rules"> & {
  /**
   * @generated from field: yuhaiin.bypass.configv2 config = 1;
   */
  config?: configv2;

  /**
   * @generated from field: repeated yuhaiin.bypass.rulev2 rules = 2;
   */
  rules: rulev2[];

  /**
   * @generated from field: map<string, yuhaiin.bypass.list> lists = 3;
   */
  lists: { [key: string]: list };
};

/**
 * Describes the message yuhaiin.backup.rules.
 * Use `create(rulesSchema)` to create a new message.
 */
export const rulesSchema: GenMessage<rules> = /*@__PURE__*/
  messageDesc(file_backup_backup, 2);

/**
 * @generated from message yuhaiin.backup.tags
 */
export type tags = Message<"yuhaiin.backup.tags"> & {
  /**
   * @generated from field: map<string, yuhaiin.tag.tags> tags = 1;
   */
  tags: { [key: string]: tags$1 };
};

/**
 * Describes the message yuhaiin.backup.tags.
 * Use `create(tagsSchema)` to create a new message.
 */
export const tagsSchema: GenMessage<tags> = /*@__PURE__*/
  messageDesc(file_backup_backup, 3);

/**
 * @generated from message yuhaiin.backup.backup_content
 */
export type backup_content = Message<"yuhaiin.backup.backup_content"> & {
  /**
   * @generated from field: yuhaiin.backup.nodes nodes = 2;
   */
  nodes?: nodes;

  /**
   * @generated from field: yuhaiin.backup.subscribes subscribes = 3;
   */
  subscribes?: subscribes;

  /**
   * @generated from field: yuhaiin.dns.dns_config_v2 dns = 4;
   */
  dns?: dns_config_v2;

  /**
   * @generated from field: yuhaiin.inbound.inbound_config inbounds = 5;
   */
  inbounds?: inbound_config;

  /**
   * @generated from field: yuhaiin.backup.rules rules = 6;
   */
  rules?: rules;

  /**
   * @generated from field: yuhaiin.backup.tags tags = 7 [json_name = "tag"];
   */
  tags?: tags;
};

/**
 * Describes the message yuhaiin.backup.backup_content.
 * Use `create(backup_contentSchema)` to create a new message.
 */
export const backup_contentSchema: GenMessage<backup_content> = /*@__PURE__*/
  messageDesc(file_backup_backup, 4);

/**
 * @generated from message yuhaiin.backup.restore_option
 */
export type restore_option = Message<"yuhaiin.backup.restore_option"> & {
  /**
   * @generated from field: bool all = 1;
   */
  all: boolean;

  /**
   * @generated from field: bool rules = 2;
   */
  rules: boolean;

  /**
   * @generated from field: bool lists = 3;
   */
  lists: boolean;

  /**
   * @generated from field: bool nodes = 4;
   */
  nodes: boolean;

  /**
   * @generated from field: bool tags = 5;
   */
  tags: boolean;

  /**
   * @generated from field: bool dns = 6;
   */
  dns: boolean;

  /**
   * @generated from field: bool inbounds = 7;
   */
  inbounds: boolean;

  /**
   * @generated from field: bool subscribes = 8;
   */
  subscribes: boolean;

  /**
   * @generated from field: yuhaiin.backup.restore_option.restore_source source = 9;
   */
  source: restore_option_restore_source;
};

/**
 * Describes the message yuhaiin.backup.restore_option.
 * Use `create(restore_optionSchema)` to create a new message.
 */
export const restore_optionSchema: GenMessage<restore_option> = /*@__PURE__*/
  messageDesc(file_backup_backup, 5);

/**
 * @generated from enum yuhaiin.backup.restore_option.restore_source
 */
export enum restore_option_restore_source {
  /**
   * @generated from enum value: unknown = 0;
   */
  unknown = 0,

  /**
   * @generated from enum value: s3 = 1;
   */
  s3 = 1,
}

/**
 * Describes the enum yuhaiin.backup.restore_option.restore_source.
 */
export const restore_option_restore_sourceSchema: GenEnum<restore_option_restore_source> = /*@__PURE__*/
  enumDesc(file_backup_backup, 5, 0);

