// @generated by protoc-gen-es v2.1.0 with parameter "target=ts"
// @generated from file tools/tools.proto (package yuhaiin.tools, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema, StringValueSchema } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file tools/tools.proto.
 */
export const file_tools_tools: GenFile = /*@__PURE__*/
  fileDesc("ChF0b29scy90b29scy5wcm90bxINeXVoYWlpbi50b29scyI6CgpJbnRlcmZhY2VzEiwKCmludGVyZmFjZXMYASADKAsyGC55dWhhaWluLnRvb2xzLkludGVyZmFjZSIsCglJbnRlcmZhY2USDAoEbmFtZRgBIAEoCRIRCglhZGRyZXNzZXMYAiADKAkynAEKBXRvb2xzEk8KF3NhdmVfcmVtb3RlX2J5cGFzc19maWxlEhwuZ29vZ2xlLnByb3RvYnVmLlN0cmluZ1ZhbHVlGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5EkIKDWdldF9pbnRlcmZhY2USFi5nb29nbGUucHJvdG9idWYuRW1wdHkaGS55dWhhaWluLnRvb2xzLkludGVyZmFjZXNCL1otZ2l0aHViLmNvbS9Bc3V0b3J1ZmEveXVoYWlpbi9wa2cvcHJvdG9zL3Rvb2xzYgZwcm90bzM", [file_google_protobuf_empty, file_google_protobuf_wrappers]);

/**
 * @generated from message yuhaiin.tools.Interfaces
 */
export type Interfaces = Message<"yuhaiin.tools.Interfaces"> & {
  /**
   * @generated from field: repeated yuhaiin.tools.Interface interfaces = 1;
   */
  interfaces: Interface[];
};

/**
 * Describes the message yuhaiin.tools.Interfaces.
 * Use `create(InterfacesSchema)` to create a new message.
 */
export const InterfacesSchema: GenMessage<Interfaces> = /*@__PURE__*/
  messageDesc(file_tools_tools, 0);

/**
 * @generated from message yuhaiin.tools.Interface
 */
export type Interface = Message<"yuhaiin.tools.Interface"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: repeated string addresses = 2;
   */
  addresses: string[];
};

/**
 * Describes the message yuhaiin.tools.Interface.
 * Use `create(InterfaceSchema)` to create a new message.
 */
export const InterfaceSchema: GenMessage<Interface> = /*@__PURE__*/
  messageDesc(file_tools_tools, 1);

/**
 * @generated from service yuhaiin.tools.tools
 */
export const tools: GenService<{
  /**
   * req: url
   *
   * @generated from rpc yuhaiin.tools.tools.save_remote_bypass_file
   */
  save_remote_bypass_file: {
    methodKind: "unary";
    input: typeof StringValueSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc yuhaiin.tools.tools.get_interface
   */
  get_interface: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof InterfacesSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_tools_tools, 0);

