// @generated by protoc-gen-es v2.2.0 with parameter "target=ts,js_import_style=legacy_commonjs"
// @generated from file statistic/grpc/config.proto (package yuhaiin.protos.statistic.service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { EmptySchema, Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { connection } from "../config_pb";
import { file_statistic_config } from "../config_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file statistic/grpc/config.proto.
 */
export const file_statistic_grpc_config: GenFile = /*@__PURE__*/
  fileDesc("ChtzdGF0aXN0aWMvZ3JwYy9jb25maWcucHJvdG8SIHl1aGFpaW4ucHJvdG9zLnN0YXRpc3RpYy5zZXJ2aWNlIi4KCnRvdGFsX2Zsb3cSEAoIZG93bmxvYWQYASABKAQSDgoGdXBsb2FkGAIgASgEIpcCCgtub3RpZnlfZGF0YRJCCgp0b3RhbF9mbG93GAMgASgLMiwueXVoYWlpbi5wcm90b3Muc3RhdGlzdGljLnNlcnZpY2UudG90YWxfZmxvd0gAEloKFm5vdGlmeV9uZXdfY29ubmVjdGlvbnMYASABKAsyOC55dWhhaWluLnByb3Rvcy5zdGF0aXN0aWMuc2VydmljZS5ub3RpZnlfbmV3X2Nvbm5lY3Rpb25zSAASYAoZbm90aWZ5X3JlbW92ZV9jb25uZWN0aW9ucxgCIAEoCzI7Lnl1aGFpaW4ucHJvdG9zLnN0YXRpc3RpYy5zZXJ2aWNlLm5vdGlmeV9yZW1vdmVfY29ubmVjdGlvbnNIAEIGCgRkYXRhIkwKFm5vdGlmeV9uZXdfY29ubmVjdGlvbnMSMgoLY29ubmVjdGlvbnMYASADKAsyHS55dWhhaWluLnN0YXRpc3RpYy5jb25uZWN0aW9uIigKGW5vdGlmeV9yZW1vdmVfY29ubmVjdGlvbnMSCwoDaWRzGAEgAygEIp4BCg5mYWlsZWRfaGlzdG9yeRIQCghwcm90b2NvbBgBIAEoCRIMCgRob3N0GAIgASgJEg0KBWVycm9yGAMgASgJEg8KB3Byb2Nlc3MYBCABKAkSKAoEdGltZRgFIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASIgoMZmFpbGVkX2NvdW50GAYgASgEUgxmYWlsZWRfY291bnQijAEKE2ZhaWxlZF9oaXN0b3J5X2xpc3QSQQoHb2JqZWN0cxgBIAMoCzIwLnl1aGFpaW4ucHJvdG9zLnN0YXRpc3RpYy5zZXJ2aWNlLmZhaWxlZF9oaXN0b3J5EjIKFGR1bXBfcHJvY2Vzc19lbmFibGVkGAIgASgIUhRkdW1wX3Byb2Nlc3NfZW5hYmxlZDLOAwoLY29ubmVjdGlvbnMSWQoFY29ubnMSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaOC55dWhhaWluLnByb3Rvcy5zdGF0aXN0aWMuc2VydmljZS5ub3RpZnlfbmV3X2Nvbm5lY3Rpb25zEmEKCmNsb3NlX2Nvbm4SOy55dWhhaWluLnByb3Rvcy5zdGF0aXN0aWMuc2VydmljZS5ub3RpZnlfcmVtb3ZlX2Nvbm5lY3Rpb25zGhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5Ek0KBXRvdGFsEhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GiwueXVoYWlpbi5wcm90b3Muc3RhdGlzdGljLnNlcnZpY2UudG90YWxfZmxvdxJRCgZub3RpZnkSFi5nb29nbGUucHJvdG9idWYuRW1wdHkaLS55dWhhaWluLnByb3Rvcy5zdGF0aXN0aWMuc2VydmljZS5ub3RpZnlfZGF0YTABEl8KDmZhaWxlZF9oaXN0b3J5EhYuZ29vZ2xlLnByb3RvYnVmLkVtcHR5GjUueXVoYWlpbi5wcm90b3Muc3RhdGlzdGljLnNlcnZpY2UuZmFpbGVkX2hpc3RvcnlfbGlzdEI7WjlnaXRodWIuY29tL0FzdXRvcnVmYS95dWhhaWluL3BrZy9wcm90b3Mvc3RhdGlzdGljL3NlcnZpY2ViBnByb3RvMw", [file_google_protobuf_empty, file_statistic_config, file_google_protobuf_timestamp]);

/**
 * @generated from message yuhaiin.protos.statistic.service.total_flow
 */
export type total_flow = Message<"yuhaiin.protos.statistic.service.total_flow"> & {
  /**
   * @generated from field: uint64 download = 1;
   */
  download: bigint;

  /**
   * @generated from field: uint64 upload = 2;
   */
  upload: bigint;
};

/**
 * Describes the message yuhaiin.protos.statistic.service.total_flow.
 * Use `create(total_flowSchema)` to create a new message.
 */
export const total_flowSchema: GenMessage<total_flow> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 0);

/**
 * @generated from message yuhaiin.protos.statistic.service.notify_data
 */
export type notify_data = Message<"yuhaiin.protos.statistic.service.notify_data"> & {
  /**
   * @generated from oneof yuhaiin.protos.statistic.service.notify_data.data
   */
  data: {
    /**
     * @generated from field: yuhaiin.protos.statistic.service.total_flow total_flow = 3;
     */
    value: total_flow;
    case: "totalFlow";
  } | {
    /**
     * @generated from field: yuhaiin.protos.statistic.service.notify_new_connections notify_new_connections = 1;
     */
    value: notify_new_connections;
    case: "notifyNewConnections";
  } | {
    /**
     * @generated from field: yuhaiin.protos.statistic.service.notify_remove_connections notify_remove_connections = 2;
     */
    value: notify_remove_connections;
    case: "notifyRemoveConnections";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message yuhaiin.protos.statistic.service.notify_data.
 * Use `create(notify_dataSchema)` to create a new message.
 */
export const notify_dataSchema: GenMessage<notify_data> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 1);

/**
 * @generated from message yuhaiin.protos.statistic.service.notify_new_connections
 */
export type notify_new_connections = Message<"yuhaiin.protos.statistic.service.notify_new_connections"> & {
  /**
   * @generated from field: repeated yuhaiin.statistic.connection connections = 1;
   */
  connections: connection[];
};

/**
 * Describes the message yuhaiin.protos.statistic.service.notify_new_connections.
 * Use `create(notify_new_connectionsSchema)` to create a new message.
 */
export const notify_new_connectionsSchema: GenMessage<notify_new_connections> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 2);

/**
 * @generated from message yuhaiin.protos.statistic.service.notify_remove_connections
 */
export type notify_remove_connections = Message<"yuhaiin.protos.statistic.service.notify_remove_connections"> & {
  /**
   * @generated from field: repeated uint64 ids = 1;
   */
  ids: bigint[];
};

/**
 * Describes the message yuhaiin.protos.statistic.service.notify_remove_connections.
 * Use `create(notify_remove_connectionsSchema)` to create a new message.
 */
export const notify_remove_connectionsSchema: GenMessage<notify_remove_connections> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 3);

/**
 * @generated from message yuhaiin.protos.statistic.service.failed_history
 */
export type failed_history = Message<"yuhaiin.protos.statistic.service.failed_history"> & {
  /**
   * @generated from field: string protocol = 1;
   */
  protocol: string;

  /**
   * @generated from field: string host = 2;
   */
  host: string;

  /**
   * @generated from field: string error = 3;
   */
  error: string;

  /**
   * @generated from field: string process = 4;
   */
  process: string;

  /**
   * @generated from field: google.protobuf.Timestamp time = 5;
   */
  time?: Timestamp;

  /**
   * @generated from field: uint64 failed_count = 6 [json_name = "failed_count"];
   */
  failedCount: bigint;
};

/**
 * Describes the message yuhaiin.protos.statistic.service.failed_history.
 * Use `create(failed_historySchema)` to create a new message.
 */
export const failed_historySchema: GenMessage<failed_history> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 4);

/**
 * @generated from message yuhaiin.protos.statistic.service.failed_history_list
 */
export type failed_history_list = Message<"yuhaiin.protos.statistic.service.failed_history_list"> & {
  /**
   * @generated from field: repeated yuhaiin.protos.statistic.service.failed_history objects = 1;
   */
  objects: failed_history[];

  /**
   * @generated from field: bool dump_process_enabled = 2 [json_name = "dump_process_enabled"];
   */
  dumpProcessEnabled: boolean;
};

/**
 * Describes the message yuhaiin.protos.statistic.service.failed_history_list.
 * Use `create(failed_history_listSchema)` to create a new message.
 */
export const failed_history_listSchema: GenMessage<failed_history_list> = /*@__PURE__*/
  messageDesc(file_statistic_grpc_config, 5);

/**
 * @generated from service yuhaiin.protos.statistic.service.connections
 */
export const connections: GenService<{
  /**
   * @generated from rpc yuhaiin.protos.statistic.service.connections.conns
   */
  conns: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof notify_new_connectionsSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.statistic.service.connections.close_conn
   */
  close_conn: {
    methodKind: "unary";
    input: typeof notify_remove_connectionsSchema;
    output: typeof EmptySchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.statistic.service.connections.total
   */
  total: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof total_flowSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.statistic.service.connections.notify
   */
  notify: {
    methodKind: "server_streaming";
    input: typeof EmptySchema;
    output: typeof notify_dataSchema;
  },
  /**
   * @generated from rpc yuhaiin.protos.statistic.service.connections.failed_history
   */
  failed_history: {
    methodKind: "unary";
    input: typeof EmptySchema;
    output: typeof failed_history_listSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_statistic_grpc_config, 0);

